// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gestion_biblioteca_api.Data;

#nullable disable

namespace gestion_biblioteca_api.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    [Migration("20251122215449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("gestion_biblioteca_api.Models.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nacionalidad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nacionalidad");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("autores");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("categorias");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Libro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AutorId")
                        .HasColumnType("int")
                        .HasColumnName("autor_id");

                    b.Property<bool>("Disponible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("diponible");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("isbn");

                    b.Property<int>("NumeroPaginas")
                        .HasColumnType("int")
                        .HasColumnName("numero_paginas");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("libros");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.LibroCategoria", b =>
                {
                    b.Property<int>("LibroId")
                        .HasColumnType("int")
                        .HasColumnName("libro_id");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria");

                    b.HasKey("LibroId", "CategoriaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("libro_categorias");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Prestamo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Devuelto")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("devuelto");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_devolucion");

                    b.Property<DateTime>("FechaPrestamo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_prestamo");

                    b.Property<int>("LibroId")
                        .HasColumnType("int")
                        .HasColumnName("libro_id");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre_usaurio");

                    b.HasKey("Id");

                    b.HasIndex("LibroId");

                    b.ToTable("prestamos");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Libro", b =>
                {
                    b.HasOne("gestion_biblioteca_api.Models.Autor", "Autor")
                        .WithMany("Libros")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.LibroCategoria", b =>
                {
                    b.HasOne("gestion_biblioteca_api.Models.Categoria", "Categoria")
                        .WithMany("LibroCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gestion_biblioteca_api.Models.Libro", "Libro")
                        .WithMany("LibroCategorias")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Prestamo", b =>
                {
                    b.HasOne("gestion_biblioteca_api.Models.Libro", "Libro")
                        .WithMany("Prestamos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Autor", b =>
                {
                    b.Navigation("Libros");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Categoria", b =>
                {
                    b.Navigation("LibroCategorias");
                });

            modelBuilder.Entity("gestion_biblioteca_api.Models.Libro", b =>
                {
                    b.Navigation("LibroCategorias");

                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
